### ISSUE TITLE
program fails to start - unhandled exception

### ISSUE THREAD

**Issue by Symbiot78** [JorgenMygindPilgaard/MemoryMate#105]
as title.
Just installed 1.7.1 and upon opening it I get the following error:

![image](https://github.com/JorgenMygindPilgaard/MemoryMate/assets/3314249/0ed2c408-50e7-4219-b469-967ee150486c)

**Comment by Symbiot78** [comment]
on windows 11.

**Comment by JorgenMygindPilgaard** [comment]
@Symbiot78 I will try to reproduce by doing a clean installation on my PC, and let you know once I know more.

**Comment by JorgenMygindPilgaard** [comment]
@Symbiot78 I have made a new release 1.7.2 wher the bug has been corrected.
https://github.com/JorgenMygindPilgaard/MemoryMate/releases/latest
